version: '3.8'

services:
  app:
    build: .
    environment:
      - DB_PATH=/app/data/kufar_bot.db
      - BOT_USERNAME=${BOT_USERNAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - KUFAR_BASE_URL=${KUFAR_BASE_URL}
      - KUFAR_CURRENCY=${KUFAR_CURRENCY}
      - KUFAR_LOWER_PRICE=${KUFAR_LOWER_PRICE}
      - KUFAR_UPPER_PRICE=${KUFAR_UPPER_PRICE}
      - CHECK_INTERVAL=${CHECK_INTERVAL}
    ports:
      - "8080:8080"
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data: